[4.14959064 3.92058289]
[3.23362003 3.10309768]
[2.68720707 2.60369631]
[2.32700159 2.26938699]
[2.07323409 2.03133439]
[1.88581762 1.85414353]
[1.74246467 1.71780375]
[1.62981891 1.61016939]
[1.53939876 1.52344977]
[1.46556383 1.45242169]
[1.40441922 1.39345402]
[1.35318981 1.34394495]
[1.30984532 1.30198183]
[1.27286641 1.26612739]
[1.24109359 1.23528083]
[1.21362671 1.20858486]
[1.18975641 1.18536199]
[1.16891612 1.16506977]
[1.15064798 1.14726884]
[1.13457795 1.13159959]
[1.12039761 1.11776494]
[1.10785039 1.10551737]
[1.09672125 1.0946491 ]
[1.08682863 1.08498449]
[1.07801829 1.07637414]
[1.07015841 1.06869024]
[1.06313579 1.06182289]
[1.05685268 1.05567713]
[1.05122435 1.0501706 ]
[1.04617707 1.04523152]
[1.04164641 1.04079718]
[1.03757592 1.03681256]
[1.03391596 1.03322929]
[1.03062281 1.03000471]
[1.02765779 1.02710108]
[1.02498667 1.02448498]
1.119957447052002
0.0837622857882142
0.19713049982383105
0.2917105829880198
0.37205458426833427
0.4411994263101268
0.5012851541839936
0.5538857631573614
0.600199240903813
0.6411630895900249
0.6775278844114072
0.7099059735437381
0.7388048151752901
0.7646504715551243
0.7878045969061054
0.8085770054810888
0.8272351630384607
0.8440114893197775
0.859109071711065
0.8727062044611424
0.8849600450114403
0.8960095961705219
0.9059781659937319
0.9149754175193331
0.9230990923584594
0.9304364718879564
0.9370656250369149
0.9430564807647952
0.9484717551927472
0.9533677572032349
0.9577950916291301
0.9617992755316952
0.9654212802439609
0.9686980096353935
0.9716627232900704
0.974345411877965
0.9767731308577021
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/ohpc/pub/apps/python/3.8.2/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/opt/ohpc/pub/apps/python/3.8.2/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/ohpc/pub/apps/python/3.8.2/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/opt/ohpc/pub/apps/python/3.8.2/lib/python3.8/site-packages/joblib/parallel.py", line 255, in __call__
    return [func(*args, **kwargs)
  File "/opt/ohpc/pub/apps/python/3.8.2/lib/python3.8/site-packages/joblib/parallel.py", line 255, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/u4/nraviles/parallel_tests_rev/fig_functions.py", line 487, in modsimpop
    deltan = deltnplussim(mi,c,U)
  File "/home/u4/nraviles/parallel_tests_rev/fig_functions.py", line 320, in deltnplussim
    comp_wld =np.random.poisson(lam=l[0],size=[comp_U,1])
  File "mtrand.pyx", line 3554, in numpy.random.mtrand.RandomState.poisson
  File "_common.pyx", line 815, in numpy.random._common.disc
  File "_common.pyx", line 377, in numpy.random._common.check_constraint
ValueError: lam < 0 or lam is NaN
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "HPC_Pfix_Simulation.py", line 98, in <module>
    element_run_abs = Parallel(n_jobs=-1)(delayed(myfun.modsimpop)(d_Inc,c_Inc,samp,parValue[parName['T']],parValue[parName['cr']],parValue[parName['b']],di[k*part:(k*part + 2)],parValue[parName['do']],((di[k*part]/di[k*part + 1])-1)/(di[k*part + 1]-1),d_max,yi_option) for k in range(subsamp)) #got rid of the minus 1
  File "/opt/ohpc/pub/apps/python/3.8.2/lib/python3.8/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/opt/ohpc/pub/apps/python/3.8.2/lib/python3.8/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/opt/ohpc/pub/apps/python/3.8.2/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/opt/ohpc/pub/apps/python/3.8.2/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/ohpc/pub/apps/python/3.8.2/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
ValueError: lam < 0 or lam is NaN
Detailed performance metrics for this job will be available at https://metrics.hpc.arizona.edu/#job_viewer?action=show&realm=SUPREMM&resource_id=73&local_job_id=2297798 by 8am on 2021/10/21.
